### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by 2642543078** [iGangao/es_text2vec_chatglm_qa#1]
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x00000208BF692130>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。))

**Comment by iGangao** [comment]
目前elasticsearch仅部署到本地服务器，你需要部署es服务器后新建索引并且上传本地知识库后才能使用

**Comment by 2642543078** [comment]
应该怎么做呢 可以写一个流程嘛

**Comment by 2642543078** [comment]
就是不是很理解你说的这个意思，是不是这个报错是因为我用的是别人的服务器，现在需要部署自己的服务器将自己本地知识进行上传呢

**Comment by iGangao** [comment]
> 就是不是很理解你说的这个意思，是不是这个报错是因为我用的是别人的服务器，现在需要部署自己的服务器将自己本地知识进行上传呢

是的，在ui.py中你可以看到初始化es的ip是本机地址，你需要运行一个es服务器（Elasticsearch），新建一个es索引，上传你的格式化数据。我的数据格式是{“title”:xx,“subtitle”:xxx, "text":xxx}。具体可以更改es文件夹下的代码，检索字段是“title”和“subtitle”，返回是“text”的数据
